### ISSUE TITLE
After updating to 1.1.2 workless badly interacts with Delayed Job

### ISSUE THREAD

**Issue by tuscland** [lostboy/workless#44]
After updating workless from 1.1.1 to 1.1.2, I get this error :

`undefined method `after_commit' for Delayed::Backend::Mongoid::Job:Class`

I am using mongoid 2.5.2, delayed_job 3.0.5 and delayed_job_mongoid 1.1.0.
